fix: update postinst, postrm, and prerm scripts for improved service management and error handling

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,49 +1,26 @@
 #!/bin/sh
-# postinst script for zswapd.
-#
-# See: dh_installdeb(1).
 
 set -e
 
-# Summary of how this script can be called:
-#        * <postinst> 'configure' <most-recently-configured-version>
-#        * <old-postinst> 'abort-upgrade' <new version>
-#        * <conflictor's-postinst> 'abort-remove' 'in-favour' <package>
-#          <new-version>
-#        * <postinst> 'abort-remove'
-#        * <deconfigured's-postinst> 'abort-deconfigure' 'in-favour'
-#          <failed-install-package> <version> 'removing'
-#          <conflicting-package> <version>
-# for details, see https://www.debian.org/doc/debian-policy/ or
-# the debian-policy package.
-
-case "${1}" in
-    configure|upgrade|reinstall|install             )
-        # Load/Reload the kernel module
-        modprobe zswap || true
-
-        # Check if zswapd is already enabled if so reload the daemon
-        case "$(systemctl is-enabled zswapd.service)" in
-            enabled             )
-                systemctl daemon-reload ; systemctl restart zswapd.service
-            ;;
-            disabled|inactive   )
-                systemctl enable --now zswapd.service
-            ;;
-            *                   )
-                echo "Unknown status, please check manually." >&2
-            ;;
-        esac
-
-    ;;
-    *                                               )
-        echo "postinst: called with unknown argument ${1}" >&2
-    ;;
+case "$1" in
+	configure|abort-upgrade|abort-deconfigure|abort-remove)
+		# This is the postinst script for zswapd package.
+		deb-systemd-helper unmask 'zswapd.service' >/dev/null || true
+		if deb-systemd-helper --quiet was-enabled 'zswapd.service'; then
+			deb-systemd-helper enable 'zswapd.service' >/dev/null || true
+		else
+			deb-systemd-helper update-state 'zswapd.service' >/dev/null || true
+		fi
+		systemctl --system daemon-reload 2> /dev/null || true
+		if [ -n "$2" ]; then
+			_dh_action=restart
+		else
+			_dh_action=start
+		fi
+		deb-systemd-invoke $_dh_action 'zswapd.service' >/dev/null || true
+	;;
+	*)
+		echo "postinst: Invalid argument $1. Use 'configure|abort-upgrade|abort-deconfigure|abort-remove'."
+		exit 1
+	;;
 esac
-
-# dh_installdeb will replace this with shell code automatically
-# generated by other debhelper scripts.
-
-#DEBHELPER#
-
-exit 0
