Switched to direct Debian package build process.

diff --git a/debian/prerm b/debian/prerm
--- a/debian/prerm
+++ b/debian/prerm
@@ -1,6 +1,20 @@
-#!/bin/bash
+#!/bin/sh
+# prerm script for zswapd.
+#
+# See: dh_installdeb(1).
 
-set -eo pipefail
+set -e
+
+# Summary of how this script can be called:
+#        * <prerm> 'remove'
+#        * <old-prerm> 'upgrade' <new-version>
+#        * <new-prerm> 'failed-upgrade' <old-version>
+#        * <conflictor's-prerm> 'remove' 'in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> 'deconfigure' 'in-favour'
+#          <package-being-installed> <version> 'removing'
+#          <conflicting-package> <version>
+# for details, see https://www.debian.org/doc/debian-policy/ or
+# the debian-policy package.
 
 case "${1}" in
     remove|deconfigure                                                  )
@@ -14,3 +28,10 @@ case "${1}" in
         echo "prerm called with unknown argument: $1" >&2 ; exit 1
     ;;
 esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
