Allow for more then one zram device to be creation and validation logic; enhance help output and default configurations

diff --git a/src/simple-zram b/src/simple-zram
--- a/src/simple-zram
+++ b/src/simple-zram
@@ -23,15 +23,6 @@ function verifyRoot () {
 
 }
 
-function validateCompression () {
-
-    case "${1}" in
-        lzo|zstd|lz4            ) return 0                                                  ;;
-        *                       ) echo "Unsupported compression algorithm: ${1}" ; return 1 ;;
-    esac
-
-}
-
 set -eo pipefail
 
 # shellcheck disable=SC1091
@@ -47,64 +38,126 @@ _usedRAM="$(awk '/Active:/ {print $2}' /proc/meminfo)"
 _availableRAM="$(( 100 - (( _usedRAM * 100 ) / _totalRAM) ))"
 
 # Default values for the script
-_swapSize=${SWAP_SIZE:-"2G"}
-_compression=${COMPRESSION:-"lzo"}
+_swapSize=${SWAP_SIZE:-"2"}
+_swapAlgorithm=${SWAP_ALGORITHM:-"lzo"}
 _swapDevices="${SWAP_DEVICES:-"1"}"
 _swapPriority=${SWAP_PRIORITY:-"100"}
 
+_copyRightInfo="$(cat <<EOF
+Copyright (C) 2024 Michael Schaecher  <michaelleeschaecher@gmail.com> GNU v3 License
+EOF
+)"
+
 _versionInfo="$(cat <<EOF
 ${_appName} - version: ${_appVersion}
+${_copyRightInfo}
+EOF
+)"
+
+_helpInfo="$(cat <<EOF
+${_versionInfo}
 This script creates and enables a zram swap device with the following parameters:
 
-Total RAM:             $(( _totalRAM / 1024000 ))GB
-Used RAM:              $(( _usedRAM / 1024000 ))GB
-Available RAM:         ${_availableRAM}%
+Usage: ${_appName} [start|stop|info|help]
 
-ZRAM Device:           $(zramctl -n | awk '{print $1}')
+Options:
+  start                   Start the zram swap device with the configured parameters
+  stop                    Stop the zram swap device and reset it
+  info                    Show version and configuration information
+  help                    Show this help message
 
-Swap Size:             ${SWAP_SIZE}
-Swap Usage:            $(free -h | awk '/Swap:/ {print $3}')
+${_copyRightInfo}
+EOF
+)"
 
-Compression Algorithm: ${COMPRESSION}
+_zramInfo="$(cat <<EOF
+${_versionInfo}
 
-Copyright (C) 2024 Michael Schaecher <michaelleeschaecher@gmail.com> GNU v3 License
+ITEM                        VALUE
+-----------------------------------------------------------
+
+Total RAM:                  $(( _totalRAM / 1024000 )) GB
+Used RAM:                   $(( _usedRAM / 1024000 )) GB
+Available RAM:              ${_availableRAM}%
+
+Devices Number:             ${_swapDevices}
+ZRAM Devices:               $(zramctl -n | awk '{print $1}')
+
+Swap Size:                  ${_swapSize} GB
+Swap Usage:                 $(free -h | awk '/Swap:/ {print $3}')
+
+Compression Algorithm:      ${_swapAlgorithm}
+
 EOF
 )"
 
 case "${1}" in
     start                   )
         verifyRoot
+        # Does a zram device already exist?
+        ! zramctl -n | grep -q '/dev/zram' || {
+            echo "ZRAM device already exists. Use '${_appName} stop' to reset it."
+            exit 0
+        }
+
+        # Validate the compression algorithm is supported.
+        case "${_swapAlgorithm}" in
+            lzo|zstd|lz4    ) ;;
+            *               ) echo "Unsupported compression algorithm: ${1}" ; return 1 ;;
+        esac
+
+        # Make sure that the required amount of RAM is available (32Gb minimum)
+        test "${_totalRAM}" -gt "33554432" || { echo "${_appName} requires at least 32MB of RAM" ; exit 1 ; }
+
+        test "${_availableRAM}" -gt "50" ||
+        { echo "${_appName} requires at least 50% of the RAM to be free" ; exit 1 ; }
+
+        # If more then 1 zram device then override swap priority
+        test "${_swapDevices}" -lt "1" || _swapPriority=$(( 100 / _swapDevices ))
+
+        _count="0"
+
+        # Create the zram devices
+        while [ "${_count}" -lt "${_swapDevices}" ] ; do
+            _device="$(zramctl --size "${_swapSize}G" --algorithm "${_swapAlgorithm}" --find ||
+            { echo "Failed to create zram device" ; exit 1 ; })"
+
+            mkswap -L SWAP "${_device}" || {
+                echo "Failed to create swap on zram device: ${_device}" ; exit 1
+            }
+
+            if test -n "${_swapPriority}" ; then
+                swapon --priority "${_swapPriority}" "${_device}" ||
+                { echo "Failed to enable swap on zram device: ${_device}" ; exit 1 ; }
+            else
+                swapon "${_device}" ||
+                { echo "Failed to enable swap on zram device: ${_device}" ; exit 1 ; }
+            fi
+
+            _count=$(( _count + 1 ))
+        done
+
     ;;
     stop                    )
         verifyRoot
 
         # Disable all zram devices and reset them
-        for device in $(zramctl -n| awk '{print $1}') ; do
-            swapoff "${device}" || { echo "Failed to disable swap on ${device}" ; exit 1 ; }
-            zramctl --reset "${device}" || { echo "Failed to reset zram device ${device}" ; exit 1 ; }
-        done
+
+        while IFS= read -r _device ; do
+            swapoff "${_device}" || { echo "Failed to disable swap on zram device: ${_device}" ; exit 1 ; }
+            zramctl --reset "${_device}" || { echo "Failed to reset zram device: ${_device}" ; exit 1 ; }
+        done < <(zramctl -n | awk '{print $1}')
 
         # Check if there is a swap partition or file
     ;;
-    info                    ) echo "${_versionInfo}" ; exit 0                            ;;
-    help                    ) echo "${_helpInfo}" ; exit 0                               ;;
+    info                    ) echo "${_zramInfo}" ; exit 0    ;;
+    version                 ) echo "${_versionInfo}" ; exit 0 ;;
+    help                    ) echo "${_helpInfo}" ; exit 0    ;;
+    *                       )
+        echo "Invalid option: ${1}"
+        echo "Use '${_appName} help' for usage information"
+        exit 1
+    ;;
 esac
-
-validateCompression "${_compression}"
-
-test "${TOTAL_RAM}" -gt "33554432" || { echo "simple-zram requires at least 32MB of RAM" ; exit 1 ; }
-
-test "${AVAILABLE_RAM}" -lt "50" ||
-{ echo "simple-zram requires at least 50% of the RAM to be free" ; exit 1 ; }
-
-if swapon --show | grep -q '/dev/zram' ; then swapoff -a ; fi
-
-# Reset the zram devices first
-while IFS= read -r LINE ; do zramctl --reset "${LINE}" ; done < <(zramctl -n | awk '{print $1}')
-
-WHICH_ZRAM="$(zramctl --size "${SWAP_SIZE}" --algorithm "${COMPRESSION}" --find ||
-{ echo "Failed to create zram device" ; exit 1 ; })"
-
-mkswap -L SWAP "${WHICH_ZRAM}" ; swapon "${WHICH_ZRAM}"
 
 exit 0
